#ifndef DISPLAY_CONSTANTS_H
#define DISPLAY_CONSTANTS_H

#ifndef NULL
  #define NULL 9999
#endif
#define DEGREE_STRING "\337"
#define DOTS ".."
#define DOTS_IN_STAGE_NAME_COUNT 2

// TODO test without
#define LCD_SET_POSITION_DELAY 20
#define LCD_CHAR_ANIMATION_DELAY 20

#define TIME_ANIMATION_INTERVAL 1000
#define LCD_CHAR_ANIMATION_INTERVAL 200
#define LCD_ANIMATION_INTERVAL 2000

#endif