#ifndef ICONS_CONSTANTS_H
#define ICONS_CONSTANTS_H

#define MASHING_ICON_INDEX 1
#define MASHING_ICON_STRING "\x01"

#define COOLING_ICON_INDEX 2
#define COOLING_ICON_STRING "\x02"

#define HEATING_ICON_INDEX 3
#define HEATING_ICON_STRING "\x03"

#define CIRCULATION_ICON_INDEX 4
#define CIRCULATION_ICON_STRING "\x04"

#define TRANSFER_ICON_INDEX 5
#define TRANSFER_ICON_STRING "\x05"

#define WATER_IN_ICON_INDEX 6
#define WATER_IN_ICON_STRING "\x06"

#define HOP_IN_ICON_INDEX 7
#define HOP_IN_ICON_STRING "\x07"

#endif
