#ifndef ICONS_CONSTANTS_H
#define ICONS_CONSTANTS_H

#define MASHING_ICON_INDEX 0
#define MASHING_ICON_STRING "\000"

#define COOLING_ICON_INDEX 1
#define COOLING_ICON_STRING "\001"

#define HEATING_ICON_INDEX 2
#define HEATING_ICON_STRING "\002"

#define CIRCULATION_ICON_INDEX 3
#define CIRCULATION_ICON_STRING "\003"

#define TRANSFER_ICON_INDEX 4
#define TRANSFER_ICON_STRING "\004"

#define WATER_IN_ICON_INDEX 5
#define WATER_IN_ICON_STRING "\005"

#define HOP_IN_ICON_INDEX 6
#define HOP_IN_ICON_STRING "\006"

#endif
